"""add:

Revision ID: 17a2e945b622
Revises: 
Create Date: 2024-12-02 15:17:19.547735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a2e945b622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('imgpath')
    op.drop_table('words1')
    op.drop_index('docname', table_name='document')
    op.drop_table('document')
    op.drop_table('user')
    op.drop_table('session')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('account', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('token', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('pet_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('session',
    sa.Column('account', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('history', mysql.TEXT(collation='utf8_unicode_ci'), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user',
    sa.Column('account', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('account'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('document',
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_unicode_ci'), nullable=False),
    sa.Column('docname', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('times', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=255), autoincrement=True, nullable=False),
    sa.Column('sort', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('docname', 'document', ['docname'], unique=True)
    op.create_table('words1',
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('kname', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('id', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('collections_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('imgpath',
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('picname', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('words',
    sa.Column('dconame', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('various', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('times', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('id', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
