/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSidebar: typeof import('./src/components/AI/AiSidebar.vue')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    Bread: typeof import('./src/components/Bread.vue')['default']
    Chat: typeof import('./src/components/AI/Chat.vue')['default']
    Chat_rag: typeof import('./src/components/AI/Chat_rag.vue')['default']
    Editor: typeof import('./src/components/ppt/editor.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ImgUpload: typeof import('./src/components/mindmap/ImgUpload/index.vue')['default']
    Ocr: typeof import('./src/components/AI/Ocr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/ppt/slider.vue')['default']
    Translate: typeof import('./src/components/AI/Translate.vue')['default']
    Vtoc: typeof import('./src/components/AI/vtoc.vue')['default']
    Write: typeof import('./src/components/AI/Write.vue')['default']
  }
}
